services:
  - type: web
    name: locker-system-web
    env: node                     # <--- เปลี่ยนเป็น node
    plan: free
    rootDir: ./
    buildCommand: "npm install"
    startCommand: "npm start"  # <--- เปลี่ยนเป็น npm start
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: locker-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: locker-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: locker-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: locker-db
          property: database
    autoDeploy: true
